### ISSUE TITLE
Carp v2 strange bad move

### ISSUE THREAD

**Issue by tissatussa** [dede1751/carp#3]
my compiled Carp v2.0.0 made a strange bad move and lost this game in CuteChess :

![Carp-strange-bad-move](https://user-images.githubusercontent.com/1109281/229780341-2a55bd5a-ac9b-4b30-8ac5-5f7a476b105a.png)

normally this game would end in a draw, but in this position Carp suddenly did Kf4 ?! and lost .. this should never happen, how could it be ?

[ i'm on Xubuntu 22.04 ]

**Comment by dede1751** [comment]
Do you by chance still have the game PGN?

**Comment by tissatussa** [comment]
yes, i ZIPped it for you : [carp-bad-move.zip](https://github.com/dede1751/carp/files/11157460/carp-bad-move.zip)

**Comment by dede1751** [comment]
Will look into this, thanks!

**Comment by tissatussa** [comment]
Note: Carp used only 0.034 seconds (?!) to play this move .. but i had set timeControl 300+3 so Carp could at least spend 3 seconds for each move in this end game ?! However, i don't know if this would have avoided the blunder ..

**Comment by dede1751** [comment]
That... Is concerning. I don't really see the reason, since carp tc is really simple and due to that it's something I'm actually working on right now. It should be really stupid and just take wtime/20 + increment/2, 0.034 seems very odd
